import type { SupportedLanguage } from "@/lib/narrationVoices";

export const BUSINESS_NAME_PLACEHOLDER = "StoryGenerator";
export const SUPPORT_EMAIL_PLACEHOLDER = "storygeneratorhelp@yahoo.com";
export const PRIVACY_EMAIL_PLACEHOLDER = "storygenerator.help@gmail.com";
export const GOVERNING_LAW_PLACEHOLDER = "Latvia";
export const RESPONSE_TIME_PLACEHOLDER = "within 24 hours";
export const BUSINESS_ADDRESS_PLACEHOLDER = "Riga, Latvia";

export type LegalSection = {
  title: string;
  paragraphs: string[];
};

export type LegalDocument = {
  badge: string;
  title: string;
  intro: string;
  lastUpdatedLabel: string;
  lastUpdatedValue: string;
  sections: LegalSection[];
};

export type SupportPageCopy = {
  badge: string;
  title: string;
  intro: string;
  supportTitle: string;
  supportBody: string;
  billingTitle: string;
  billingBody: string;
  privacyTitle: string;
  privacyBody: string;
  responseTitle: string;
  responseBody: string;
  legalTitle: string;
  legalBody: string;
};

export type LegalNavCopy = {
  privacy: string;
  terms: string;
  refunds: string;
  support: string;
  allRightsReserved: string;
  supportEmailLabel: string;
};

export type LegalTranslations = {
  footer: LegalNavCopy;
  support: SupportPageCopy;
  privacy: LegalDocument;
  terms: LegalDocument;
  refunds: LegalDocument;
};

const LAST_UPDATED = "March 14, 2026";

function doc(
  title: string,
  intro: string,
  lastUpdatedLabel: string,
  sections: LegalSection[],
  badge = "Legal"
): LegalDocument {
  return {
    badge,
    title,
    intro,
    lastUpdatedLabel,
    lastUpdatedValue: LAST_UPDATED,
    sections
  };
}

const en: LegalTranslations = {
  footer: {
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    refunds: "Refund & Cancellation",
    support: "Contact & Support",
    allRightsReserved: "All rights reserved.",
    supportEmailLabel: "Support"
  },
  support: {
    badge: "Support",
    title: "Contact & Support",
    intro: "If you need help with billing, account questions, story access, or privacy requests, this is the fastest way to reach the team.",
    supportTitle: "General support",
    supportBody: `Email ${SUPPORT_EMAIL_PLACEHOLDER} for account help, technical issues, or questions about using the service.`,
    billingTitle: "Billing support",
    billingBody: "For subscription questions, plan changes, cancellation timing, or duplicate charges, contact support and include the email used for Stripe billing.",
    privacyTitle: "Privacy requests",
    privacyBody: `For personal data requests, deletion requests, or privacy questions, email ${PRIVACY_EMAIL_PLACEHOLDER}.`,
    responseTitle: "Response time",
    responseBody: `We aim to reply ${RESPONSE_TIME_PLACEHOLDER}.`,
    legalTitle: "Business details",
    legalBody: `${BUSINESS_NAME_PLACEHOLDER}. ${BUSINESS_ADDRESS_PLACEHOLDER}`
  },
  privacy: doc("Privacy Policy", "This policy explains what data we collect, how we use it, and how we handle billing and story-generation information.", "Last updated", [
    { title: "Who operates the service", paragraphs: [`${BUSINESS_NAME_PLACEHOLDER} operates this website and the digital story-generation service.`, `If you have questions about this policy, contact ${PRIVACY_EMAIL_PLACEHOLDER}.`] },
    { title: "What information we collect", paragraphs: ["We may collect account identifiers, subscription and billing metadata, customer support messages, and the story prompts or settings that users submit while generating stories.", "We may also collect technical diagnostics such as device, browser, IP address, timestamps, and application logs needed to operate, secure, and improve the service."] },
    { title: "Billing, payments, and story inputs", paragraphs: ["Payments are processed by Stripe. We do not store full card numbers on our own servers, but we may store Stripe customer IDs, subscription IDs, plan details, billing interval, and payment status.", "When you enter names, themes, ages, or other story inputs, we use that information to generate personalized content and related assets such as narration and downloads."] },
    { title: "How we use data", paragraphs: ["We use information to provide the service, generate stories, manage subscriptions, answer support requests, prevent abuse, and improve reliability and product quality.", "Where applicable, we process data because it is necessary to perform our contract with you, because we have a legitimate interest in operating and securing the service, or because you have provided consent."] },
    { title: "Retention, rights, and third parties", paragraphs: ["We keep personal data only as long as reasonably necessary to operate the service, comply with legal obligations, resolve disputes, and enforce our agreements.", `Depending on your location, you may have rights to access, correct, delete, restrict, or object to certain processing. To make a request, contact ${PRIVACY_EMAIL_PLACEHOLDER}. We may use Stripe and other infrastructure, analytics, logging, or AI providers to deliver the service.`] }
  ]),
  terms: doc("Terms of Service", "These terms govern access to the website, story-generation tools, subscriptions, and related digital features.", "Last updated", [
    { title: "Service description", paragraphs: ["The service provides personalized children's story generation, related downloadable assets, and Premium subscription features delivered digitally through the website.", "No physical goods are shipped."] },
    { title: "User responsibilities and acceptable use", paragraphs: ["You are responsible for the information you submit, your use of generated content, and keeping your access details secure.", "You may not attempt to bypass usage limits, reverse engineer the service, interfere with the platform, scrape content at scale, or use the service to create illegal or infringing material."] },
    { title: "Intellectual property and subscriptions", paragraphs: [`The website, software, branding, interface, and service design remain the property of ${BUSINESS_NAME_PLACEHOLDER} or its licensors.`, "Premium subscriptions renew automatically on the selected billing interval until cancelled. Prices and available plans are shown during checkout and may be updated prospectively."] },
    { title: "Cancellation, suspension, and liability", paragraphs: ["You can manage or cancel your subscription through the Stripe Customer Portal. If you cancel, access normally continues until the end of the current paid billing period unless local law requires otherwise.", `We may suspend or terminate access for fraud, abuse, non-payment, legal risk, or violations of these terms. To the maximum extent permitted by law, ${BUSINESS_NAME_PLACEHOLDER} will not be liable for indirect, incidental, special, consequential, or punitive damages arising from use of the service.`] },
    { title: "Governing law and contact", paragraphs: [`These terms are governed by ${GOVERNING_LAW_PLACEHOLDER}, unless mandatory consumer law requires otherwise.`, `For legal or support questions, contact ${SUPPORT_EMAIL_PLACEHOLDER}.`] }
  ]),
  refunds: doc("Refund and Cancellation Policy", "This policy explains how subscription billing, cancellation, and refund requests work for this digital service.", "Last updated", [
    { title: "Subscription billing", paragraphs: ["Premium is offered as a recurring digital subscription with monthly or yearly billing, depending on the plan you choose at checkout.", "Your subscription renews automatically unless cancelled before the next renewal date."] },
    { title: "How to cancel", paragraphs: ["You can cancel your subscription at any time through the Stripe Customer Portal linked from the billing area of the site.", "If you need help cancelling, contact support and we will help you find the correct billing account."] },
    { title: "When cancellation takes effect", paragraphs: ["If you cancel, the cancellation normally takes effect at the end of the current paid billing period.", "Unless otherwise required by law, we do not normally provide prorated refunds for unused time in an active billing period."] },
    { title: "Refund policy", paragraphs: ["Because this is a digital subscription product with immediate access to Premium features, refunds are generally limited and may be granted only at our discretion or where required by law.", "If you believe you were charged in error, billed twice, or experienced a technical issue that prevented access, contact support with the billing email and transaction details."] },
    { title: "Billing support", paragraphs: [`For billing questions, cancellation help, or refund requests, contact ${SUPPORT_EMAIL_PLACEHOLDER}.`] }
  ])
};

const ru: LegalTranslations = {
  footer: {
    privacy: "Политика конфиденциальности",
    terms: "Условия использования",
    refunds: "Возврат и отмена",
    support: "Контакты и поддержка",
    allRightsReserved: "Все права защищены.",
    supportEmailLabel: "Поддержка"
  },
  support: {
    badge: "Поддержка",
    title: "Контакты и поддержка",
    intro: "Если вам нужна помощь с оплатой, доступом, историями или вопросами по персональным данным, здесь собраны основные способы связи.",
    supportTitle: "Общая поддержка",
    supportBody: `Напишите на ${SUPPORT_EMAIL_PLACEHOLDER}, если нужна помощь с аккаунтом, техническими проблемами или использованием сервиса.`,
    billingTitle: "Помощь по оплате",
    billingBody: "По вопросам подписки, смены плана, времени отмены или списаний свяжитесь с поддержкой и укажите адрес электронной почты, использованный при оплате через Stripe.",
    privacyTitle: "Запросы по персональным данным",
    privacyBody: `По вопросам удаления данных, доступа к данным или приватности пишите на ${PRIVACY_EMAIL_PLACEHOLDER}.`,
    responseTitle: "Срок ответа",
    responseBody: `Обычно мы отвечаем ${RESPONSE_TIME_PLACEHOLDER}.`,
    legalTitle: "Реквизиты",
    legalBody: `${BUSINESS_NAME_PLACEHOLDER}. ${BUSINESS_ADDRESS_PLACEHOLDER}`
  },
  privacy: doc("Политика конфиденциальности", "В этом документе описано, какие данные мы собираем, как используем их и как обрабатываем сведения об оплате и создании историй.", "Последнее обновление", [
    { title: "Кто управляет сервисом", paragraphs: [`${BUSINESS_NAME_PLACEHOLDER} управляет этим сайтом и цифровым сервисом генерации детских историй.`, `Если у вас есть вопросы по этой политике, напишите на ${PRIVACY_EMAIL_PLACEHOLDER}.`] },
    { title: "Какие данные мы собираем", paragraphs: ["Мы можем собирать идентификаторы аккаунта, метаданные подписки и оплаты, сообщения в поддержку, а также сюжетные запросы и настройки, которые пользователь отправляет при создании историй.", "Мы также можем собирать технические данные, такие как устройство, браузер, IP-адрес, временные метки и журналы приложения, необходимые для работы, безопасности и улучшения сервиса."] },
    { title: "Оплата, платежи и данные историй", paragraphs: ["Платежи обрабатываются Stripe. Мы не храним полные данные банковских карт на собственных серверах, но можем хранить идентификатор клиента Stripe, идентификатор подписки Stripe, сведения о тарифе, интервале оплаты и статусе платежа.", "Когда вы вводите имена, темы, возраст или другие параметры истории, мы используем эту информацию для создания персонализированного контента и связанных материалов, таких как озвучка и загрузки."] },
    { title: "Как мы используем данные", paragraphs: ["Мы используем данные для предоставления сервиса, генерации историй, управления подписками, ответов на обращения в поддержку, предотвращения злоупотреблений и улучшения качества продукта.", "Если это применимо, мы обрабатываем данные, потому что это необходимо для исполнения договора с вами, потому что у нас есть законный интерес в работе и защите сервиса, или потому что вы дали согласие."] },
    { title: "Хранение, права и сторонние сервисы", paragraphs: ["Мы храним персональные данные только столько, сколько это разумно необходимо для работы сервиса, соблюдения закона, разрешения споров и исполнения наших соглашений.", `В зависимости от вашей юрисдикции у вас могут быть права на доступ, исправление, удаление, ограничение обработки или возражение против определённых способов обработки персональных данных. Чтобы отправить запрос, напишите на ${PRIVACY_EMAIL_PLACEHOLDER}. Для работы сервиса мы можем использовать Stripe и других провайдеров инфраструктуры, аналитики, логирования или сервисов искусственного интеллекта.`] }
  ], "Документы"),
  terms: doc("Условия использования", "Эти условия регулируют доступ к сайту, генерации историй, подпискам и связанным цифровым функциям.", "Последнее обновление", [
    { title: "Описание сервиса", paragraphs: ["Сервис предоставляет цифровую генерацию персонализированных детских историй, связанные загружаемые материалы и функции подписки Premium через сайт.", "Физические товары не доставляются."] },
    { title: "Ответственность пользователя и допустимое использование", paragraphs: ["Вы несёте ответственность за информацию, которую отправляете, за использование сгенерированного контента и за сохранность своих данных доступа.", "Запрещается обходить лимиты использования, пытаться реверс-инжинирить сервис, мешать работе платформы, массово собирать контент или использовать сервис для создания незаконных либо нарушающих права материалов."] },
    { title: "Интеллектуальная собственность и подписка", paragraphs: [`Сайт, программное обеспечение, бренд, интерфейс и дизайн сервиса остаются собственностью ${BUSINESS_NAME_PLACEHOLDER} или его лицензиаров.`, "Подписка Premium продлевается автоматически с выбранным интервалом оплаты, пока не будет отменена. Цены и доступные тарифы показываются во время оформления оплаты и могут быть изменены на будущее."] },
    { title: "Отмена, приостановка и ответственность", paragraphs: ["Вы можете управлять подпиской или отменить её через клиентский портал Stripe. Если вы отменяете подписку, доступ обычно сохраняется до конца уже оплаченного периода, если местное право не требует иного.", `Мы можем приостановить или прекратить доступ в случае мошенничества, злоупотреблений, неуплаты, правовых рисков или нарушения этих условий. В максимально допустимой законом степени ${BUSINESS_NAME_PLACEHOLDER} не несёт ответственности за косвенные, случайные, специальные, последующие или штрафные убытки, связанные с использованием сервиса.`] },
    { title: "Применимое право и контакты", paragraphs: [`Эти условия регулируются правом ${GOVERNING_LAW_PLACEHOLDER}, если обязательные нормы потребительского права не требуют иного.`, `По юридическим вопросам и вопросам поддержки пишите на ${SUPPORT_EMAIL_PLACEHOLDER}.`] }
  ], "Документы"),
  refunds: doc("Политика возврата и отмены", "Здесь описано, как работает списание по подписке, отмена и рассмотрение запросов на возврат для цифрового сервиса.", "Последнее обновление", [
    { title: "Подписка и списания", paragraphs: ["Premium предлагается как регулярная цифровая подписка с ежемесячной или ежегодной оплатой в зависимости от выбранного плана.", "Подписка продлевается автоматически, если не отменить её до следующей даты списания."] },
    { title: "Как отменить подписку", paragraphs: ["Вы можете отменить подписку в любое время через клиентский портал Stripe, ссылка на который доступна в разделе оплаты на сайте.", "Если вам нужна помощь с отменой, свяжитесь с поддержкой, и мы поможем найти нужный платёжный аккаунт."] },
    { title: "Когда отмена вступает в силу", paragraphs: ["После отмены подписка обычно действует до конца текущего оплаченного периода.", "Если иное не требуется законом, мы обычно не предоставляем пропорциональные возвраты за неиспользованное время внутри активного периода."] },
    { title: "Политика возвратов", paragraphs: ["Поскольку это цифровой подписочный продукт с немедленным доступом к функциям Premium, возвраты обычно ограничены и предоставляются только по нашему усмотрению либо в случаях, когда этого требует закон.", "Если вы считаете, что с вас ошибочно списали деньги, списали оплату дважды или техническая проблема помешала получить доступ, свяжитесь с поддержкой и укажите адрес электронной почты для оплаты и детали транзакции."] },
    { title: "Поддержка по вопросам оплаты", paragraphs: [`По вопросам списаний, отмены или возвратов пишите на ${SUPPORT_EMAIL_PLACEHOLDER}.`] }
  ], "Документы")
};

const es: LegalTranslations = {
  footer: { privacy: "Politica de privacidad", terms: "Terminos del servicio", refunds: "Reembolsos y cancelacion", support: "Contacto y soporte", allRightsReserved: "Todos los derechos reservados.", supportEmailLabel: "Soporte" },
  support: { badge: "Soporte", title: "Contacto y soporte", intro: "Si necesitas ayuda con pagos, acceso, historias o privacidad, aqui tienes la forma mas rapida de contactar con el equipo.", supportTitle: "Soporte general", supportBody: `Escribe a ${SUPPORT_EMAIL_PLACEHOLDER} para ayuda con la cuenta, problemas tecnicos o preguntas sobre el servicio.`, billingTitle: "Soporte de facturacion", billingBody: "Para dudas sobre suscripciones, cambios de plan, cancelaciones o cobros duplicados, contacta con soporte e indica el correo usado en Stripe.", privacyTitle: "Solicitudes de privacidad", privacyBody: `Para solicitudes de datos personales o privacidad, escribe a ${PRIVACY_EMAIL_PLACEHOLDER}.`, responseTitle: "Tiempo de respuesta", responseBody: `Intentamos responder ${RESPONSE_TIME_PLACEHOLDER}.`, legalTitle: "Datos del negocio", legalBody: `${BUSINESS_NAME_PLACEHOLDER}. ${BUSINESS_ADDRESS_PLACEHOLDER}` },
  privacy: doc("Politica de privacidad", "Esta politica explica que datos recogemos, como los usamos y como tratamos la informacion de pago y generacion de historias.", "Ultima actualizacion", [{ title: "Quien opera el servicio", paragraphs: [`${BUSINESS_NAME_PLACEHOLDER} opera este sitio web y el servicio digital de generacion de historias.`, `Si tienes preguntas sobre esta politica, escribe a ${PRIVACY_EMAIL_PLACEHOLDER}.`] }, { title: "Que informacion recopilamos", paragraphs: ["Podemos recopilar identificadores de cuenta, metadatos de suscripcion y facturacion, mensajes de soporte y los prompts o ajustes que el usuario envia al generar historias.", "Tambien podemos recopilar datos tecnicos como dispositivo, navegador, direccion IP, marcas de tiempo y registros de la aplicacion para operar, proteger y mejorar el servicio."] }, { title: "Pagos e informacion de historias", paragraphs: ["Los pagos se procesan mediante Stripe. No guardamos numeros completos de tarjeta en nuestros servidores, pero podemos almacenar IDs de cliente y suscripcion de Stripe, plan, intervalo de facturacion y estado del pago.", "Cuando introduces nombres, temas, edades u otros datos de la historia, usamos esa informacion para generar contenido personalizado y recursos relacionados como narracion y descargas."] }, { title: "Como usamos los datos", paragraphs: ["Usamos la informacion para prestar el servicio, generar historias, gestionar suscripciones, responder solicitudes de soporte, prevenir abusos y mejorar la calidad del producto.", "Cuando corresponde, tratamos datos porque es necesario para ejecutar nuestro contrato contigo, porque tenemos un interes legitimo en operar y proteger el servicio o porque has dado tu consentimiento."] }, { title: "Conservacion, derechos y terceros", paragraphs: ["Conservamos los datos personales solo durante el tiempo razonablemente necesario para operar el servicio, cumplir obligaciones legales, resolver disputas y hacer cumplir nuestros acuerdos.", `Segun tu ubicacion, puedes tener derechos de acceso, correccion, eliminacion, limitacion u oposicion a ciertos tratamientos. Para ejercerlos, escribe a ${PRIVACY_EMAIL_PLACEHOLDER}. Podemos utilizar Stripe y otros proveedores de infraestructura, analitica, registros o IA para prestar el servicio.`] }]),
  terms: doc("Terminos del servicio", "Estos terminos regulan el acceso al sitio, la generacion de historias, las suscripciones y las funciones digitales relacionadas.", "Ultima actualizacion", [{ title: "Descripcion del servicio", paragraphs: ["El servicio ofrece generacion personalizada de historias infantiles, recursos descargables relacionados y funciones Premium entregadas digitalmente a traves del sitio.", "No se envian productos fisicos."] }, { title: "Responsabilidades del usuario y uso aceptable", paragraphs: ["Eres responsable de la informacion que envias, del uso que haces del contenido generado y de mantener seguras tus credenciales de acceso.", "No puedes intentar eludir limites de uso, realizar ingenieria inversa, interferir con la plataforma, extraer contenido a gran escala ni usar el servicio para crear material ilegal o infractor."] }, { title: "Propiedad intelectual y suscripciones", paragraphs: [`El sitio, el software, la marca, la interfaz y el diseno del servicio pertenecen a ${BUSINESS_NAME_PLACEHOLDER} o a sus licenciantes.`, "Las suscripciones Premium se renuevan automaticamente segun el intervalo elegido hasta que se cancelen. Los precios y planes disponibles se muestran durante el checkout y pueden actualizarse para el futuro."] }, { title: "Cancelacion, suspension y responsabilidad", paragraphs: ["Puedes gestionar o cancelar tu suscripcion mediante el Stripe Customer Portal. Si cancelas, el acceso normalmente continua hasta el final del periodo ya pagado, salvo que la ley local exija otra cosa.", `Podemos suspender o finalizar el acceso por fraude, abuso, impago, riesgo legal o incumplimiento de estos terminos. En la maxima medida permitida por la ley, ${BUSINESS_NAME_PLACEHOLDER} no sera responsable de danos indirectos, incidentales, especiales, consecuentes o punitivos derivados del uso del servicio.`] }, { title: "Ley aplicable y contacto", paragraphs: [`Estos terminos se rigen por ${GOVERNING_LAW_PLACEHOLDER}, salvo que la normativa imperativa de consumo exija otra cosa.`, `Para preguntas legales o de soporte, escribe a ${SUPPORT_EMAIL_PLACEHOLDER}.`] }]),
  refunds: doc("Politica de reembolsos y cancelacion", "Esta politica explica como funcionan la facturacion de suscripciones, la cancelacion y las solicitudes de reembolso para este servicio digital.", "Ultima actualizacion", [{ title: "Facturacion de la suscripcion", paragraphs: ["Premium se ofrece como una suscripcion digital recurrente con cobro mensual o anual, segun el plan elegido.", "La suscripcion se renueva automaticamente salvo cancelacion antes de la siguiente fecha de renovacion."] }, { title: "Como cancelar", paragraphs: ["Puedes cancelar tu suscripcion en cualquier momento desde el Stripe Customer Portal enlazado en la zona de facturacion del sitio.", "Si necesitas ayuda para cancelar, contacta con soporte y te ayudaremos a localizar la cuenta correcta."] }, { title: "Cuando surte efecto la cancelacion", paragraphs: ["La cancelacion normalmente surte efecto al final del periodo de facturacion ya pagado.", "Salvo que la ley disponga lo contrario, no solemos ofrecer reembolsos prorrateados por tiempo no usado dentro de un periodo activo."] }, { title: "Politica de reembolso", paragraphs: ["Como se trata de un producto digital por suscripcion con acceso inmediato a funciones Premium, los reembolsos suelen ser limitados y se conceden solo a nuestra discrecion o cuando la ley lo exige.", "Si crees que hubo un cobro erroneo, un cobro duplicado o un problema tecnico que impidio el acceso, contacta con soporte e incluye el email de facturacion y los detalles de la transaccion."] }, { title: "Soporte de facturacion", paragraphs: [`Para preguntas sobre cobros, cancelacion o reembolsos, escribe a ${SUPPORT_EMAIL_PLACEHOLDER}.`] }])
};

const de: LegalTranslations = {
  footer: { privacy: "Datenschutz", terms: "Nutzungsbedingungen", refunds: "Rueckerstattung und Kuendigung", support: "Kontakt und Support", allRightsReserved: "Alle Rechte vorbehalten.", supportEmailLabel: "Support" },
  support: { badge: "Support", title: "Kontakt und Support", intro: "Hier erreichst du uns bei Fragen zu Zahlung, Zugriff, Datenschutz oder technischen Problemen am schnellsten.", supportTitle: "Allgemeiner Support", supportBody: `Schreibe an ${SUPPORT_EMAIL_PLACEHOLDER} fuer Hilfe bei Konto, Technik oder Nutzung des Dienstes.`, billingTitle: "Billing-Support", billingBody: "Bei Fragen zu Abos, Tarifwechseln, Kuendigungen oder doppelten Abbuchungen wende dich an den Support und nenne die fuer Stripe verwendete E-Mail.", privacyTitle: "Datenschutzanfragen", privacyBody: `Fuer Datenschutzfragen oder Datenanfragen schreibe an ${PRIVACY_EMAIL_PLACEHOLDER}.`, responseTitle: "Antwortzeit", responseBody: `Wir antworten in der Regel ${RESPONSE_TIME_PLACEHOLDER}.`, legalTitle: "Unternehmensdaten", legalBody: `${BUSINESS_NAME_PLACEHOLDER}. ${BUSINESS_ADDRESS_PLACEHOLDER}` },
  privacy: doc("Datenschutzerklaerung", "Diese Erklaerung beschreibt, welche Daten wir erfassen, wie wir sie nutzen und wie wir Zahlungs- und Story-Daten behandeln.", "Letzte Aktualisierung", [{ title: "Wer den Dienst betreibt", paragraphs: [`${BUSINESS_NAME_PLACEHOLDER} betreibt diese Website und den digitalen Story-Generator.`, `Wenn du Fragen zu dieser Richtlinie hast, schreibe an ${PRIVACY_EMAIL_PLACEHOLDER}.`] }, { title: "Welche Informationen wir erfassen", paragraphs: ["Wir koennen Kontokennungen, Abo- und Abrechnungsdaten, Support-Nachrichten sowie Story-Prompts und Einstellungen erfassen, die Nutzer beim Erstellen von Geschichten eingeben.", "Ausserdem koennen wir technische Diagnosedaten wie Geraet, Browser, IP-Adresse, Zeitstempel und Anwendungsprotokolle erfassen, um den Dienst zu betreiben, zu schuetzen und zu verbessern."] }, { title: "Zahlungen und Story-Eingaben", paragraphs: ["Zahlungen werden ueber Stripe verarbeitet. Wir speichern keine vollstaendigen Kartennummern auf unseren eigenen Servern, koennen aber Stripe-Kunden- und Abo-IDs, Tarifinformationen, Abrechnungsintervalle und Zahlungsstatus speichern.", "Wenn du Namen, Themen, Alter oder andere Story-Angaben eingibst, verwenden wir diese Informationen zur Erstellung personalisierter Inhalte und zugehoeriger Dateien wie Audio und Downloads."] }, { title: "Wie wir Daten verwenden", paragraphs: ["Wir verwenden Informationen, um den Dienst bereitzustellen, Geschichten zu erzeugen, Abos zu verwalten, Support-Anfragen zu beantworten, Missbrauch zu verhindern und die Produktqualitaet zu verbessern.", "Soweit anwendbar, verarbeiten wir Daten, weil dies fuer die Vertragserfuellung notwendig ist, weil wir ein berechtigtes Interesse am sicheren Betrieb des Dienstes haben oder weil du eingewilligt hast."] }, { title: "Speicherung, Rechte und Drittanbieter", paragraphs: ["Wir speichern personenbezogene Daten nur so lange, wie es fuer den Betrieb des Dienstes, die Einhaltung gesetzlicher Pflichten, die Beilegung von Streitigkeiten und die Durchsetzung unserer Vereinbarungen erforderlich ist.", `Abhaengig von deinem Standort hast du moeglicherweise Rechte auf Auskunft, Berichtigung, Loeschung, Einschraenkung oder Widerspruch. Fuer Anfragen schreibe an ${PRIVACY_EMAIL_PLACEHOLDER}. Wir koennen Stripe sowie weitere Infrastruktur-, Analyse-, Logging- oder KI-Anbieter einsetzen.`] }]),
  terms: doc("Nutzungsbedingungen", "Diese Bedingungen regeln den Zugang zur Website, Story-Generierung, Abos und verwandte digitale Funktionen.", "Letzte Aktualisierung", [{ title: "Beschreibung des Dienstes", paragraphs: ["Der Dienst bietet personalisierte Kindergeschichten, zugehoerige Downloads und Premium-Funktionen, die digital ueber die Website bereitgestellt werden.", "Es werden keine physischen Waren versendet."] }, { title: "Pflichten der Nutzer und zulaessige Nutzung", paragraphs: ["Du bist fuer die von dir uebermittelten Informationen, die Nutzung der generierten Inhalte und die Sicherheit deiner Zugangsdaten verantwortlich.", "Du darfst keine Nutzungslimits umgehen, den Dienst nicht rueckentwickeln, die Plattform nicht stoeren, keine Inhalte in grossem Umfang auslesen und den Dienst nicht fuer rechtswidrige oder rechtsverletzende Inhalte verwenden."] }, { title: "Geistiges Eigentum und Abonnements", paragraphs: [`Website, Software, Marke, Benutzeroberflaeche und Servicedesign bleiben Eigentum von ${BUSINESS_NAME_PLACEHOLDER} oder seiner Lizenzgeber.`, "Premium-Abonnements verlaengern sich automatisch nach dem gewaehlten Abrechnungsintervall, bis sie gekuendigt werden. Preise und verfuegbare Plaene werden beim Checkout angezeigt und koennen fuer die Zukunft angepasst werden."] }, { title: "Kuendigung, Sperrung und Haftung", paragraphs: ["Du kannst dein Abo ueber das Stripe Customer Portal verwalten oder kuendigen. Bei einer Kuendigung bleibt der Zugang normalerweise bis zum Ende des bereits bezahlten Zeitraums bestehen, sofern lokales Recht nichts anderes verlangt.", `Wir koennen den Zugang bei Betrug, Missbrauch, Nichtzahlung, rechtlichem Risiko oder Verstoessen gegen diese Bedingungen sperren oder beenden. Soweit gesetzlich zulaessig, haftet ${BUSINESS_NAME_PLACEHOLDER} nicht fuer indirekte, zufaellige, besondere, Folge- oder Strafschaeden aus der Nutzung des Dienstes.`] }, { title: "Anwendbares Recht und Kontakt", paragraphs: [`Diese Bedingungen unterliegen ${GOVERNING_LAW_PLACEHOLDER}, sofern zwingendes Verbraucherrecht nichts anderes verlangt.`, `Fuer rechtliche Fragen oder Support schreibe an ${SUPPORT_EMAIL_PLACEHOLDER}.`] }]),
  refunds: doc("Rueckerstattungs- und Kuendigungsrichtlinie", "Diese Richtlinie erklaert, wie Abo-Abrechnung, Kuendigung und Rueckerstattungsanfragen fuer diesen digitalen Dienst funktionieren.", "Letzte Aktualisierung", [{ title: "Abo-Abrechnung", paragraphs: ["Premium wird als wiederkehrendes digitales Abo mit monatlicher oder jaehrlicher Abrechnung angeboten, je nach gewaehltem Tarif.", "Das Abo verlaengert sich automatisch, sofern es nicht vor dem naechsten Verlaengerungsdatum gekuendigt wird."] }, { title: "Wie du kuendigst", paragraphs: ["Du kannst dein Abo jederzeit ueber das Stripe Customer Portal kuendigen, das im Billing-Bereich der Website verlinkt ist.", "Wenn du Hilfe bei der Kuendigung brauchst, kontaktiere den Support und wir helfen dir, das richtige Billing-Konto zu finden."] }, { title: "Wann die Kuendigung wirksam wird", paragraphs: ["Eine Kuendigung wird normalerweise zum Ende des aktuell bezahlten Abrechnungszeitraums wirksam.", "Sofern gesetzlich nicht anders vorgeschrieben, bieten wir in der Regel keine anteiligen Rueckerstattungen fuer ungenutzte Zeit innerhalb eines aktiven Zeitraums an."] }, { title: "Rueckerstattungsrichtlinie", paragraphs: ["Da es sich um ein digitales Abo mit sofortigem Zugang zu Premium-Funktionen handelt, sind Rueckerstattungen in der Regel eingeschraenkt und werden nur nach unserem Ermessen oder sofern gesetzlich erforderlich gewaehrt.", "Wenn du glaubst, dass du falsch belastet wurdest, doppelt bezahlt hast oder ein technisches Problem den Zugang verhindert hat, kontaktiere den Support mit deiner Billing-E-Mail und den Transaktionsdetails."] }, { title: "Billing-Support", paragraphs: [`Bei Fragen zu Zahlungen, Kuendigung oder Rueckerstattungen schreibe an ${SUPPORT_EMAIL_PLACEHOLDER}.`] }])
};

const fr: LegalTranslations = {
  footer: { privacy: "Confidentialite", terms: "Conditions d'utilisation", refunds: "Remboursement et resiliation", support: "Contact et support", allRightsReserved: "Tous droits reserves.", supportEmailLabel: "Support" },
  support: { badge: "Support", title: "Contact et support", intro: "Pour les questions de paiement, d'acces, de support technique ou de confidentialite, voici le moyen le plus rapide de joindre l'equipe.", supportTitle: "Support general", supportBody: `Ecrivez a ${SUPPORT_EMAIL_PLACEHOLDER} pour l'aide sur le compte, les problemes techniques ou l'utilisation du service.`, billingTitle: "Support facturation", billingBody: "Pour les questions d'abonnement, de changement d'offre, de resiliation ou de double paiement, contactez le support avec l'email utilise dans Stripe.", privacyTitle: "Demandes de confidentialite", privacyBody: `Pour les demandes relatives aux donnees personnelles, ecrivez a ${PRIVACY_EMAIL_PLACEHOLDER}.`, responseTitle: "Delai de reponse", responseBody: `Nous essayons de repondre ${RESPONSE_TIME_PLACEHOLDER}.`, legalTitle: "Informations de l'entreprise", legalBody: `${BUSINESS_NAME_PLACEHOLDER}. ${BUSINESS_ADDRESS_PLACEHOLDER}` },
  privacy: doc("Politique de confidentialite", "Cette politique explique quelles donnees nous collectons, comment nous les utilisons et comment nous traitons les informations de paiement et de generation d'histoires.", "Derniere mise a jour", [{ title: "Qui exploite le service", paragraphs: [`${BUSINESS_NAME_PLACEHOLDER} exploite ce site et le service numerique de generation d'histoires.`, `Si vous avez des questions sur cette politique, ecrivez a ${PRIVACY_EMAIL_PLACEHOLDER}.`] }, { title: "Quelles informations nous collectons", paragraphs: ["Nous pouvons collecter des identifiants de compte, des metadonnees d'abonnement et de facturation, des messages au support ainsi que les prompts et reglages envoyes lors de la generation d'histoires.", "Nous pouvons aussi collecter des donnees techniques comme l'appareil, le navigateur, l'adresse IP, les horodatages et les journaux applicatifs afin d'exploiter, proteger et ameliorer le service."] }, { title: "Paiement et donnees de story", paragraphs: ["Les paiements sont traites par Stripe. Nous ne stockons pas les numeros complets de carte sur nos propres serveurs, mais nous pouvons conserver les identifiants client et abonnement Stripe, le plan, l'intervalle de facturation et l'etat du paiement.", "Lorsque vous saisissez des noms, themes, ages ou autres informations de story, nous utilisons ces donnees pour generer un contenu personnalise et des ressources associees comme la narration et les telechargements."] }, { title: "Comment nous utilisons les donnees", paragraphs: ["Nous utilisons les informations pour fournir le service, generer des histoires, gerer les abonnements, repondre au support, prevenir les abus et ameliorer la qualite du produit.", "Lorsque cela s'applique, nous traitons les donnees parce que cela est necessaire a l'execution du contrat, parce que nous avons un interet legitime a exploiter et securiser le service, ou parce que vous avez donne votre consentement."] }, { title: "Conservation, droits et tiers", paragraphs: ["Nous conservons les donnees personnelles uniquement pendant la duree raisonnablement necessaire pour exploiter le service, respecter nos obligations legales, resoudre les litiges et faire appliquer nos accords.", `Selon votre lieu de residence, vous pouvez disposer de droits d'acces, de rectification, de suppression, de limitation ou d'opposition. Pour exercer ces droits, ecrivez a ${PRIVACY_EMAIL_PLACEHOLDER}. Nous pouvons utiliser Stripe et d'autres fournisseurs d'infrastructure, d'analytique, de journalisation ou d'IA pour fournir le service.`] }]),
  terms: doc("Conditions d'utilisation", "Ces conditions regissent l'acces au site, la generation d'histoires, les abonnements et les fonctions numeriques associees.", "Derniere mise a jour", [{ title: "Description du service", paragraphs: ["Le service fournit la generation personnalisee d'histoires pour enfants, des ressources telechargeables associees et des fonctionnalites Premium livrees numeriquement via le site.", "Aucun bien physique n'est expedie."] }, { title: "Responsabilites de l'utilisateur et usage acceptable", paragraphs: ["Vous etes responsable des informations que vous soumettez, de l'utilisation du contenu genere et de la securite de vos identifiants d'acces.", "Vous ne pouvez pas contourner les limites d'utilisation, retroconcevoir le service, perturber la plateforme, aspirer du contenu a grande echelle ou utiliser le service pour creer du contenu illegal ou contrefaisant."] }, { title: "Propriete intellectuelle et abonnements", paragraphs: [`Le site, le logiciel, la marque, l'interface et la conception du service restent la propriete de ${BUSINESS_NAME_PLACEHOLDER} ou de ses concédants.`, "Les abonnements Premium se renouvellent automatiquement selon l'intervalle choisi jusqu'a leur resiliation. Les prix et offres disponibles sont affiches au moment du checkout et peuvent etre modifies pour l'avenir."] }, { title: "Resiliation, suspension et responsabilite", paragraphs: ["Vous pouvez gerer ou annuler votre abonnement via le Stripe Customer Portal. En cas d'annulation, l'acces continue normalement jusqu'a la fin de la periode deja payee, sauf si la loi locale exige autre chose.", `Nous pouvons suspendre ou resilier l'acces en cas de fraude, d'abus, de non-paiement, de risque juridique ou de violation des presentes conditions. Dans la mesure maximale permise par la loi, ${BUSINESS_NAME_PLACEHOLDER} ne sera pas responsable des dommages indirects, accessoires, speciaux, consecutifs ou punitifs lies a l'utilisation du service.`] }, { title: "Droit applicable et contact", paragraphs: [`Ces conditions sont regies par ${GOVERNING_LAW_PLACEHOLDER}, sauf si des regles imperatives de droit de la consommation imposent autre chose.`, `Pour toute question juridique ou de support, ecrivez a ${SUPPORT_EMAIL_PLACEHOLDER}.`] }]),
  refunds: doc("Politique de remboursement et de resiliation", "Cette politique explique comment fonctionnent la facturation d'abonnement, la resiliation et les demandes de remboursement pour ce service numerique.", "Derniere mise a jour", [{ title: "Facturation de l'abonnement", paragraphs: ["Premium est propose sous forme d'abonnement numerique recurrent avec facturation mensuelle ou annuelle selon l'offre choisie.", "Votre abonnement se renouvelle automatiquement sauf annulation avant la prochaine date de renouvellement."] }, { title: "Comment resilier", paragraphs: ["Vous pouvez resilier votre abonnement a tout moment via le Stripe Customer Portal lie depuis la zone de facturation du site.", "Si vous avez besoin d'aide pour resilier, contactez le support et nous vous aiderons a retrouver le bon compte de facturation."] }, { title: "Quand la resiliation prend effet", paragraphs: ["La resiliation prend normalement effet a la fin de la periode de facturation deja payee.", "Sauf obligation legale contraire, nous n'accordons generalement pas de remboursement au prorata pour le temps non utilise pendant une periode active."] }, { title: "Politique de remboursement", paragraphs: ["Comme il s'agit d'un produit numerique par abonnement avec acces immediat aux fonctionnalites Premium, les remboursements sont generalement limites et accordes uniquement a notre discretion ou lorsque la loi l'exige.", "Si vous pensez avoir ete facture par erreur, facture deux fois ou empeche d'acceder au service a cause d'un probleme technique, contactez le support avec l'email de facturation et les details de la transaction."] }, { title: "Support facturation", paragraphs: [`Pour toute question de paiement, de resiliation ou de remboursement, ecrivez a ${SUPPORT_EMAIL_PLACEHOLDER}.`] }])
};

const it: LegalTranslations = {
  footer: { privacy: "Privacy", terms: "Termini di servizio", refunds: "Rimborsi e cancellazione", support: "Contatti e supporto", allRightsReserved: "Tutti i diritti riservati.", supportEmailLabel: "Supporto" },
  support: { badge: "Supporto", title: "Contatti e supporto", intro: "Per domande su pagamenti, accesso, storie o privacy, questo e il modo piu rapido per contattare il team.", supportTitle: "Supporto generale", supportBody: `Scrivi a ${SUPPORT_EMAIL_PLACEHOLDER} per aiuto su account, problemi tecnici o uso del servizio.`, billingTitle: "Supporto fatturazione", billingBody: "Per dubbi su abbonamenti, cambio piano, cancellazione o doppi addebiti, contatta il supporto indicando l'email usata in Stripe.", privacyTitle: "Richieste privacy", privacyBody: `Per richieste sui dati personali o sulla privacy, scrivi a ${PRIVACY_EMAIL_PLACEHOLDER}.`, responseTitle: "Tempo di risposta", responseBody: `Cerchiamo di rispondere ${RESPONSE_TIME_PLACEHOLDER}.`, legalTitle: "Dati aziendali", legalBody: `${BUSINESS_NAME_PLACEHOLDER}. ${BUSINESS_ADDRESS_PLACEHOLDER}` },
  privacy: doc("Informativa sulla privacy", "Questa informativa spiega quali dati raccogliamo, come li usiamo e come trattiamo pagamenti e dati di generazione delle storie.", "Ultimo aggiornamento", [{ title: "Chi gestisce il servizio", paragraphs: [`${BUSINESS_NAME_PLACEHOLDER} gestisce questo sito e il servizio digitale di generazione di storie.`, `Se hai domande su questa informativa, scrivi a ${PRIVACY_EMAIL_PLACEHOLDER}.`] }, { title: "Quali informazioni raccogliamo", paragraphs: ["Possiamo raccogliere identificativi dell'account, metadati di abbonamento e fatturazione, messaggi al supporto e i prompt o le impostazioni inviati durante la generazione delle storie.", "Possiamo anche raccogliere dati tecnici come dispositivo, browser, indirizzo IP, timestamp e log applicativi necessari per gestire, proteggere e migliorare il servizio."] }, { title: "Pagamenti e dati delle storie", paragraphs: ["I pagamenti sono elaborati da Stripe. Non memorizziamo numeri completi di carta sui nostri server, ma possiamo conservare Stripe customer ID, subscription ID, piano, intervallo di fatturazione e stato del pagamento.", "Quando inserisci nomi, temi, eta o altri dettagli della storia, usiamo tali informazioni per generare contenuti personalizzati e risorse correlate come audio e download."] }, { title: "Come usiamo i dati", paragraphs: ["Usiamo le informazioni per fornire il servizio, generare storie, gestire gli abbonamenti, rispondere al supporto, prevenire abusi e migliorare la qualita del prodotto.", "Quando applicabile, trattiamo i dati per eseguire il contratto con te, per il nostro legittimo interesse a gestire e proteggere il servizio oppure sulla base del tuo consenso."] }, { title: "Conservazione, diritti e terze parti", paragraphs: ["Conserviamo i dati personali solo per il tempo ragionevolmente necessario a gestire il servizio, rispettare obblighi legali, risolvere controversie e far valere i nostri accordi.", `A seconda della tua posizione, potresti avere diritti di accesso, rettifica, cancellazione, limitazione o opposizione. Per esercitarli, scrivi a ${PRIVACY_EMAIL_PLACEHOLDER}. Possiamo usare Stripe e altri fornitori di infrastruttura, analisi, logging o AI per offrire il servizio.`] }]),
  terms: doc("Termini di servizio", "Questi termini regolano l'accesso al sito, la generazione di storie, gli abbonamenti e le funzioni digitali correlate.", "Ultimo aggiornamento", [{ title: "Descrizione del servizio", paragraphs: ["Il servizio offre generazione personalizzata di storie per bambini, contenuti scaricabili correlati e funzionalita Premium fornite digitalmente tramite il sito.", "Non vengono spediti beni fisici."] }, { title: "Responsabilita dell'utente e uso consentito", paragraphs: ["Sei responsabile delle informazioni che invii, dell'uso dei contenuti generati e della sicurezza delle tue credenziali di accesso.", "Non puoi aggirare i limiti di utilizzo, effettuare reverse engineering del servizio, interferire con la piattaforma, estrarre contenuti su larga scala o usare il servizio per creare materiale illecito o in violazione di diritti."] }, { title: "Proprieta intellettuale e abbonamenti", paragraphs: [`Il sito, il software, il marchio, l'interfaccia e il design del servizio restano di proprieta di ${BUSINESS_NAME_PLACEHOLDER} o dei suoi licenzianti.`, "Gli abbonamenti Premium si rinnovano automaticamente secondo l'intervallo scelto finche non vengono annullati. Prezzi e piani disponibili sono mostrati durante il checkout e possono essere aggiornati per il futuro."] }, { title: "Cancellazione, sospensione e responsabilita", paragraphs: ["Puoi gestire o annullare l'abbonamento tramite lo Stripe Customer Portal. In caso di cancellazione, l'accesso continua normalmente fino alla fine del periodo gia pagato, salvo diverse disposizioni di legge.", `Possiamo sospendere o terminare l'accesso in caso di frode, abuso, mancato pagamento, rischio legale o violazione di questi termini. Nella misura massima consentita dalla legge, ${BUSINESS_NAME_PLACEHOLDER} non sara responsabile per danni indiretti, incidentali, speciali, consequenziali o punitivi derivanti dall'uso del servizio.`] }, { title: "Legge applicabile e contatti", paragraphs: [`Questi termini sono regolati da ${GOVERNING_LAW_PLACEHOLDER}, salvo diverse norme imperative a tutela dei consumatori.`, `Per questioni legali o di supporto, scrivi a ${SUPPORT_EMAIL_PLACEHOLDER}.`] }]),
  refunds: doc("Politica di rimborso e cancellazione", "Questa politica spiega come funzionano fatturazione, cancellazione e richieste di rimborso per questo servizio digitale.", "Ultimo aggiornamento", [{ title: "Fatturazione dell'abbonamento", paragraphs: ["Premium e offerto come abbonamento digitale ricorrente con fatturazione mensile o annuale, in base al piano scelto.", "L'abbonamento si rinnova automaticamente salvo cancellazione prima della successiva data di rinnovo."] }, { title: "Come annullare", paragraphs: ["Puoi annullare l'abbonamento in qualsiasi momento tramite lo Stripe Customer Portal collegato dall'area billing del sito.", "Se hai bisogno di aiuto per annullare, contatta il supporto e ti aiuteremo a trovare l'account corretto."] }, { title: "Quando la cancellazione ha effetto", paragraphs: ["La cancellazione ha normalmente effetto alla fine del periodo di fatturazione gia pagato.", "Salvo obblighi di legge, in genere non offriamo rimborsi proporzionali per il tempo non utilizzato in un periodo attivo."] }, { title: "Politica di rimborso", paragraphs: ["Poiche si tratta di un prodotto digitale in abbonamento con accesso immediato alle funzionalita Premium, i rimborsi sono generalmente limitati e concessi solo a nostra discrezione o quando richiesti dalla legge.", "Se ritieni di essere stato addebitato per errore, due volte o di non aver potuto accedere al servizio per un problema tecnico, contatta il supporto includendo l'email di fatturazione e i dettagli della transazione."] }, { title: "Supporto fatturazione", paragraphs: [`Per domande su addebiti, cancellazione o rimborsi, scrivi a ${SUPPORT_EMAIL_PLACEHOLDER}.`] }])
};

const pt: LegalTranslations = {
  footer: { privacy: "Privacidade", terms: "Termos de servico", refunds: "Reembolso e cancelamento", support: "Contacto e suporte", allRightsReserved: "Todos os direitos reservados.", supportEmailLabel: "Suporte" },
  support: { badge: "Suporte", title: "Contacto e suporte", intro: "Se precisares de ajuda com pagamentos, acesso, historias ou privacidade, este e o caminho mais rapido para falar com a equipa.", supportTitle: "Suporte geral", supportBody: `Escreve para ${SUPPORT_EMAIL_PLACEHOLDER} para ajuda com a conta, problemas tecnicos ou uso do servico.`, billingTitle: "Suporte de cobranca", billingBody: "Para duvidas sobre assinaturas, mudancas de plano, cancelamento ou cobrancas duplicadas, contacta o suporte com o email usado no Stripe.", privacyTitle: "Pedidos de privacidade", privacyBody: `Para pedidos sobre dados pessoais ou privacidade, escreve para ${PRIVACY_EMAIL_PLACEHOLDER}.`, responseTitle: "Tempo de resposta", responseBody: `Tentamos responder ${RESPONSE_TIME_PLACEHOLDER}.`, legalTitle: "Dados do negocio", legalBody: `${BUSINESS_NAME_PLACEHOLDER}. ${BUSINESS_ADDRESS_PLACEHOLDER}` },
  privacy: doc("Politica de privacidade", "Esta politica explica que dados recolhemos, como os usamos e como tratamos informacoes de pagamento e criacao de historias.", "Ultima atualizacao", [{ title: "Quem opera o servico", paragraphs: [`${BUSINESS_NAME_PLACEHOLDER} opera este site e o servico digital de geracao de historias.`, `Se tiveres perguntas sobre esta politica, escreve para ${PRIVACY_EMAIL_PLACEHOLDER}.`] }, { title: "Que informacoes recolhemos", paragraphs: ["Podemos recolher identificadores de conta, metadados de assinatura e cobranca, mensagens de suporte e os prompts ou definicoes enviados ao gerar historias.", "Tambem podemos recolher dados tecnicos como dispositivo, navegador, endereco IP, marcas temporais e registos da aplicacao para operar, proteger e melhorar o servico."] }, { title: "Pagamentos e dados das historias", paragraphs: ["Os pagamentos sao processados pela Stripe. Nao guardamos numeros completos de cartao nos nossos servidores, mas podemos armazenar Stripe customer ID, subscription ID, plano, intervalo de cobranca e estado do pagamento.", "Quando inseres nomes, temas, idades ou outros detalhes da historia, usamos essas informacoes para gerar conteudo personalizado e recursos relacionados, como narracao e downloads."] }, { title: "Como usamos os dados", paragraphs: ["Usamos a informacao para prestar o servico, gerar historias, gerir assinaturas, responder ao suporte, prevenir abusos e melhorar a qualidade do produto.", "Quando aplicavel, tratamos os dados porque isso e necessario para executar o contrato contigo, porque temos um interesse legitimo em operar e proteger o servico, ou porque deste consentimento."] }, { title: "Retencao, direitos e terceiros", paragraphs: ["Guardamos os dados pessoais apenas durante o tempo razoavelmente necessario para operar o servico, cumprir obrigacoes legais, resolver disputas e fazer cumprir os nossos acordos.", `Dependendo da tua localizacao, podes ter direitos de acesso, correcao, eliminacao, limitacao ou oposicao. Para exercer esses direitos, escreve para ${PRIVACY_EMAIL_PLACEHOLDER}. Podemos usar Stripe e outros fornecedores de infraestrutura, analitica, logging ou IA para prestar o servico.`] }]),
  terms: doc("Termos de servico", "Estes termos regulam o acesso ao site, a geracao de historias, as assinaturas e as funcionalidades digitais relacionadas.", "Ultima atualizacao", [{ title: "Descricao do servico", paragraphs: ["O servico oferece geracao personalizada de historias infantis, recursos descarregaveis relacionados e funcionalidades Premium fornecidas digitalmente atraves do site.", "Nao ha envio de bens fisicos."] }, { title: "Responsabilidades do utilizador e uso aceitavel", paragraphs: ["Es responsavel pelas informacoes que envias, pelo uso do conteudo gerado e pela seguranca das tuas credenciais de acesso.", "Nao podes contornar limites de utilizacao, fazer engenharia inversa do servico, interferir com a plataforma, recolher conteudo em massa nem usar o servico para criar material ilegal ou que viole direitos."] }, { title: "Propriedade intelectual e assinaturas", paragraphs: [`O site, o software, a marca, a interface e o design do servico continuam a ser propriedade de ${BUSINESS_NAME_PLACEHOLDER} ou dos seus licenciadores.`, "As assinaturas Premium renovam-se automaticamente de acordo com o intervalo escolhido ate serem canceladas. Os precos e planos disponiveis sao mostrados durante o checkout e podem ser atualizados para o futuro."] }, { title: "Cancelamento, suspensao e responsabilidade", paragraphs: ["Podes gerir ou cancelar a tua assinatura atraves do Stripe Customer Portal. Em caso de cancelamento, o acesso continua normalmente ate ao fim do periodo ja pago, salvo se a lei local exigir outra coisa.", `Podemos suspender ou terminar o acesso em caso de fraude, abuso, falta de pagamento, risco legal ou violacao destes termos. Na medida maxima permitida por lei, ${BUSINESS_NAME_PLACEHOLDER} nao sera responsavel por danos indiretos, incidentais, especiais, consequenciais ou punitivos decorrentes do uso do servico.`] }, { title: "Lei aplicavel e contacto", paragraphs: [`Estes termos sao regidos por ${GOVERNING_LAW_PLACEHOLDER}, salvo se normas imperativas de defesa do consumidor exigirem o contrario.`, `Para questoes legais ou de suporte, escreve para ${SUPPORT_EMAIL_PLACEHOLDER}.`] }]),
  refunds: doc("Politica de reembolso e cancelamento", "Esta politica explica como funcionam cobrancas, cancelamento e pedidos de reembolso para este servico digital.", "Ultima atualizacao", [{ title: "Cobranca da assinatura", paragraphs: ["O Premium e oferecido como assinatura digital recorrente com cobranca mensal ou anual, consoante o plano escolhido.", "A assinatura renova-se automaticamente salvo cancelamento antes da proxima data de renovacao."] }, { title: "Como cancelar", paragraphs: ["Podes cancelar a tua assinatura a qualquer momento atraves do Stripe Customer Portal ligado na area de billing do site.", "Se precisares de ajuda para cancelar, contacta o suporte e ajudaremos a localizar a conta correta."] }, { title: "Quando o cancelamento entra em vigor", paragraphs: ["O cancelamento entra normalmente em vigor no final do periodo de cobranca ja pago.", "Salvo obrigacao legal em contrario, normalmente nao oferecemos reembolsos proporcionais por tempo nao utilizado durante um periodo ativo."] }, { title: "Politica de reembolso", paragraphs: ["Como se trata de um produto digital por assinatura com acesso imediato a funcionalidades Premium, os reembolsos sao geralmente limitados e concedidos apenas ao nosso criterio ou quando exigidos por lei.", "Se achares que foste cobrado por erro, cobrado duas vezes ou impedido de aceder ao servico devido a um problema tecnico, contacta o suporte com o email de faturacao e os detalhes da transacao."] }, { title: "Suporte de cobranca", paragraphs: [`Para questoes de cobranca, cancelamento ou reembolso, escreve para ${SUPPORT_EMAIL_PLACEHOLDER}.`] }])
};

const zh: LegalTranslations = {
  footer: { privacy: "隐私政策", terms: "服务条款", refunds: "退款与取消政策", support: "联系与支持", allRightsReserved: "保留所有权利。", supportEmailLabel: "支持邮箱" },
  support: { badge: "支持", title: "联系与支持", intro: "如果你需要账单帮助、账户协助、故事访问支持或隐私相关帮助，这里是最快的联系入口。", supportTitle: "一般支持", supportBody: `如需账户帮助、技术支持或使用问题，请发送邮件至 ${SUPPORT_EMAIL_PLACEHOLDER}。`, billingTitle: "账单支持", billingBody: "如果你对订阅、套餐切换、取消时间或重复扣费有疑问，请联系支持并提供用于 Stripe 付款的邮箱。", privacyTitle: "隐私请求", privacyBody: `如需提出数据访问、删除或隐私相关请求，请发送邮件至 ${PRIVACY_EMAIL_PLACEHOLDER}。`, responseTitle: "回复时间", responseBody: `我们通常会在 ${RESPONSE_TIME_PLACEHOLDER} 内回复。`, legalTitle: "企业信息", legalBody: `${BUSINESS_NAME_PLACEHOLDER}。${BUSINESS_ADDRESS_PLACEHOLDER}` },
  privacy: doc("隐私政策", "本政策说明我们收集哪些数据、如何使用这些数据，以及如何处理付款和故事生成相关信息。", "最后更新", [{ title: "谁在运营本服务", paragraphs: [`${BUSINESS_NAME_PLACEHOLDER} 负责运营本网站和数字化儿童故事生成服务。`, `如果你对本政策有任何疑问，请发送邮件至 ${PRIVACY_EMAIL_PLACEHOLDER}。`] }, { title: "我们收集哪些信息", paragraphs: ["我们可能会收集账户标识信息、订阅和账单元数据、客服消息，以及用户在生成故事时提交的提示词和设置。", "我们还可能收集设备、浏览器、IP 地址、时间戳和应用日志等技术诊断信息，以便运行、保护和改进服务。"] }, { title: "账单、付款和故事输入", paragraphs: ["付款由 Stripe 处理，我们不会在自己的服务器上存储完整的银行卡号，但可能保存 Stripe 客户标识、Stripe 订阅标识、套餐信息、计费周期和付款状态。", "当你输入姓名、主题、年龄或其他故事信息时，我们会使用这些内容来生成个性化故事以及相关资源，例如语音和下载文件。"] }, { title: "我们如何使用数据", paragraphs: ["我们使用这些信息来提供服务、生成故事、管理订阅、回复支持请求、防止滥用，并提升产品质量和稳定性。", "在适用的情况下，我们处理数据的依据可能包括履行与你的合同、保护和运营服务的合法利益，或你已经给予同意。"] }, { title: "保存期限、你的权利与第三方", paragraphs: ["我们仅会在为运营服务、履行法律义务、解决争议和执行协议所合理必要的期限内保留个人数据。", `根据你所在地区的法律，你可能享有访问、更正、删除、限制处理或反对某些个人数据处理活动的权利。如需提出请求，请联系 ${PRIVACY_EMAIL_PLACEHOLDER}。我们也可能使用 Stripe 及其他基础设施、分析、日志或人工智能服务提供商来支持本服务。`] }], "法律"),
  terms: doc("服务条款", "这些条款适用于网站访问、故事生成工具、订阅服务以及相关数字功能。", "最后更新", [{ title: "服务说明", paragraphs: ["本服务通过网站提供个性化儿童故事生成、相关下载内容和 Premium 订阅功能。", "我们不提供任何实物发货。"] }, { title: "用户责任与可接受使用规则", paragraphs: ["你需要对自己提交的信息、对生成内容的使用方式以及账户访问凭据的安全负责。", "你不得试图绕过使用限制、逆向工程本服务、干扰平台运行、批量抓取内容，或利用本服务生成违法或侵权材料。"] }, { title: "知识产权与订阅", paragraphs: [`网站、软件、品牌、界面和服务设计归 ${BUSINESS_NAME_PLACEHOLDER} 或其许可方所有。`, "Premium 订阅会按照你选择的计费周期自动续费，直到你取消为止。价格和可用套餐会在付款页面展示，并可能在未来调整。"] }, { title: "取消、暂停与责任限制", paragraphs: ["你可以通过 Stripe 客户门户管理或取消订阅。除非当地法律另有要求，取消后访问权限通常会持续到当前已支付周期结束。", `如发生欺诈、滥用、不付款、法律风险或违反这些条款的情况，我们可以暂停或终止访问。在法律允许的最大范围内，${BUSINESS_NAME_PLACEHOLDER} 不对因使用本服务而产生的任何间接、附带、特殊、后果性或惩罚性损害承担责任。`] }, { title: "适用法律与联系方式", paragraphs: [`除非强制性消费者保护法另有要求，这些条款受 ${GOVERNING_LAW_PLACEHOLDER} 约束。`, `如有法律或支持相关问题，请联系 ${SUPPORT_EMAIL_PLACEHOLDER}。`] }], "法律"),
  refunds: doc("退款与取消政策", "本政策说明此数字订阅服务的计费、取消和退款申请如何处理。", "最后更新", [{ title: "订阅计费", paragraphs: ["Premium 以数字订阅形式提供，可按月或按年计费，具体取决于你选择的方案。", "除非你在下一次续费前取消，否则订阅会自动续费。"] }, { title: "如何取消", paragraphs: ["你可以随时通过网站账单区域中的 Stripe 客户门户链接取消订阅。", "如果你需要取消帮助，请联系支持，我们会帮助你找到正确的账单账户。"] }, { title: "取消何时生效", paragraphs: ["如果你取消订阅，取消通常会在当前已支付计费周期结束时生效。", "除非法律另有要求，我们通常不会对当前计费周期内未使用的时间提供按比例退款。"] }, { title: "退款政策", paragraphs: ["由于这是一个购买后即可立即使用 Premium 功能的数字订阅产品，退款通常受到限制，只会在我们酌情决定或法律要求的情况下提供。", "如果你认为自己被错误扣费、被重复收费，或因技术问题无法访问服务，请联系支持并提供账单邮箱和交易详情。"] }, { title: "账单支持", paragraphs: [`如有扣费、取消或退款问题，请联系 ${SUPPORT_EMAIL_PLACEHOLDER}。`] }], "法律")
};

export const legalTranslations: Record<SupportedLanguage, LegalTranslations> = {
  en,
  ru,
  es,
  de,
  fr,
  it,
  pt,
  zh
};

export function getLegalTranslations(locale: SupportedLanguage): LegalTranslations {
  return legalTranslations[locale] || legalTranslations.en;
}
